spring.application.name=ProductManagement

server.port = 3002

spring.datasource.url=jdbc:mysql://localhost:3306/productmanagement
spring.datasource.username=muni.mysql
spring.datasource.password=muni200
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.data.web.pageable.serialization-mode=via-dto